---
name: Paperless-ngx
version: dev
slug: paperless-ngx
url: https://github.com/paperless-ngx/paperless-ngx
init: false
ingress: true
description:
  Paperless is an application that manages your personal documents. With
  the help of a document scanner, paperless transforms your wieldy physical document
  binders into a searchable archive and provides many utilities for finding and managing
  your documents.
arch:
  - aarch64
  - amd64
startup: system
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web interface
map:
  - share:rw
options:
  filename: "{created_year}/{correspondent}/{title}"
  language: eng
  language_packages: eng deu fra ita spa
  default_superuser:
    username:
    email:
    password:
  timezone: UTC
schema:
  url: str?
  filename: str
  language: str
  language_packages: str
  default_superuser:
    username: str
    email: email
    password: password
  timezone: str
  polling_interval: int?
  barcodes_enabled: bool?
  barcodes_asn: bool?
  consumer_recursive: bool?
  consumer_subdirs_as_tags: bool?
